### ISSUE TITLE
Pagination/Filtering not working in VM environment

### ISSUE THREAD

**Issue by kadamwhite** [kadamwhite/wpapi-vagrant-varietal#4]
These URLs all return the exact same results after the first `vagrant up`:
- http://wpapi.loc/wp-json/wp/v2/posts
- http://wpapi.loc/wp-json/wp/v2/posts?page=2
- http://wpapi.loc/wp-json/wp/v2/posts?page=3

Filtering is broken too. This should not be the case. I am unclear on what could be causing this problem.

**Comment by kadamwhite** [comment]
c.f. https://github.com/WP-API/WP-API/issues/1926

**Comment by danielbachhuber** [comment]
Where is the Nginx config?

**Comment by kadamwhite** [comment]
@danielbachhuber config here: https://github.com/kadamwhite/wpapi-vagrant-varietal/blob/master/deploy/roles/nginx/templates/nginx.conf

**Comment by kadamwhite** [comment]
UUuuuggggh. Got it.

``` diff
diff --git a/deploy/roles/nginx/templates/nginx.conf b/deploy/roles/nginx/templates/nginx.conf
index 5ab780c..5db9956 100644
--- a/deploy/roles/nginx/templates/nginx.conf
+++ b/deploy/roles/nginx/templates/nginx.conf
@@ -11,7 +11,7 @@ server {

    location / {
        index index.php index.html index.htm;
-       try_files $uri $uri/ /index.php$args;
+       try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
```

And with that, the final work day of the year comes to a close. Thanks for the direction to look at the config more closely, @danielbachhuber, I owe you one.
